export const altText = {
  "/images/hero/hero-open-field.jpg": "A lone person walks through a wide meadow beneath a pale, clouded sky.",
  "/images/hero/hero-open-field-mobile.jpg": "A lone person walks through a wide meadow beneath a pale, clouded sky.",
  "/images/hero/hero-consult-room.jpg": "Two oatmeal armchairs face one another in a quiet, naturally lit consultation room.",
  "/images/editorial/editorial-bigtype-field.jpg": "A person rests in an open field beneath distant hills and a pale sky.",
  "/images/editorial/editorial-tangled-thoughts.jpg": "A monochrome figure in a white shirt has a dense tangle of cable in place of a head.",
  "/images/editorial/editorial-footer-field.jpg": "A person sits at a wooden desk in an otherwise empty grassy field.",
  "/images/editorial/editorial-window-light.jpg": "Soft window light falls across a quiet wall beside a small potted plant.",
  "/images/editorial/editorial-two-chairs.jpg": "A close view of two linen armchair arms with a narrow space between them.",
  "/images/illustration/illo-overwhelm.svg": "A worried figure holds their head, surrounded by small doodles of tangled thoughts.",
  "/images/illustration/illo-starting-line.svg": "Three runners in different outfits crouch at the starting line.",
  "/images/illustration/illo-diagonal-rider.svg": "A relaxed skateboarder in green trousers glides down a gentle slope.",
  "/images/illustration/illo-step-01-listen.svg": "Two people sit facing each other, one speaking and one listening.",
  "/images/illustration/illo-step-02-match.svg": "A small figure looks toward two puzzle pieces that almost fit together.",
  "/images/illustration/illo-step-03-continue.svg": "A tangled line unwinds into a clear path with a small figure walking along it.",
  "/images/editorial/editorial-loose-thread.jpg": "The same monochrome figure has a single calm loop of cable in place of a head.",
  "/images/illustration/illo-empty-appointments.svg": "An empty calendar with one green dot sits beside a small plant.",
  "/images/illustration/illo-404.svg": "A small figure stands where a path ends, with a green dot just ahead.",
  "/images/journal/journal-01.jpg": "An empty park bench faces a quiet lawn.",
  "/images/journal/journal-02.jpg": "Two hands loosely hold a white ceramic mug on an oak table.",
  "/images/journal/journal-03.jpg": "Rumpled white linen rests on an unmade bed beside a window.",
  "/images/journal/journal-04.jpg": "A narrow gravel path winds through grass over a low rise.",
  "/images/journal/journal-05.jpg": "A plain notebook and pencil lie on an otherwise empty desk.",
  "/images/journal/journal-06.jpg": "Rain beads on a window with a soft green field beyond.",
  "/images/team/therapist-01.jpg": "AI-generated layout placeholder portrait of a woman with short dark curls; replace before launch.",
  "/images/team/therapist-02.jpg": "AI-generated layout placeholder portrait of a man with a greying beard and glasses; replace before launch.",
  "/images/team/therapist-03.jpg": "AI-generated layout placeholder portrait of a woman with long straight black hair; replace before launch.",
  "/images/team/therapist-04.jpg": "AI-generated layout placeholder portrait of a man with close-cropped hair; replace before launch.",
  "/images/team/therapist-05.jpg": "AI-generated layout placeholder portrait of a woman with a silver bob; replace before launch.",
  "/images/team/therapist-06.jpg": "AI-generated layout placeholder portrait of a person with shoulder-length auburn hair; replace before launch.",
  "/images/texture/texture-torn-edge.png": "Decorative torn paper edge.",
  "/images/team/avatar-01.jpg": "AI-generated layout placeholder avatar 1; replace before launch.",
  "/images/team/avatar-02.jpg": "AI-generated layout placeholder avatar 2; replace before launch.",
  "/images/team/avatar-03.jpg": "AI-generated layout placeholder avatar 3; replace before launch.",
  "/images/team/avatar-04.jpg": "AI-generated layout placeholder avatar 4; replace before launch.",
  "/images/team/avatar-05.jpg": "AI-generated layout placeholder avatar 5; replace before launch.",
  "/images/texture/texture-halftone-dots.png": "Decorative halftone dots.",
  "/icons/anxiety.svg": "anxiety icon",
  "/icons/assessment.svg": "assessment icon",
  "/icons/breathing.svg": "breathing icon",
  "/icons/burnout.svg": "burnout icon",
  "/icons/calendar.svg": "calendar icon",
  "/icons/clock.svg": "clock icon",
  "/icons/couples.svg": "couples icon",
  "/icons/focus.svg": "focus icon",
  "/icons/follow-up.svg": "follow up icon",
  "/icons/grief.svg": "grief icon",
  "/icons/growth.svg": "growth icon",
  "/icons/low-mood.svg": "low mood icon",
  "/icons/matching.svg": "matching icon",
  "/icons/notes.svg": "notes icon",
  "/icons/privacy.svg": "privacy icon",
  "/icons/relationships.svg": "relationships icon",
  "/icons/self-esteem.svg": "self esteem icon",
  "/icons/session-in-person.svg": "session in person icon",
  "/icons/session-phone.svg": "session phone icon",
  "/icons/session-video.svg": "session video icon",
  "/icons/sleep.svg": "sleep icon",
  "/icons/stress.svg": "stress icon",
  "/icons/teens.svg": "teens icon",
  "/icons/trauma.svg": "trauma icon",
  "/brand/apple-touch-icon-180.png": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/favicon-32.png": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/favicon.svg": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/icon-512.png": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/og-default.jpg": "Openfield — Room to think.",
  "/brand/og-default.svg": "Openfield — Room to think.",
  "/brand/openfield-mark-512.svg": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/openfield-mark-light-512.svg": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/openfield-mark-light.svg": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/openfield-mark.svg": "Openfield symbol: a knot unwinding into a straight line.",
  "/brand/openfield-wordmark-light.svg": "Openfield.",
  "/brand/openfield-wordmark.svg": "Openfield."
} as const;
