-- Keep the managed appointments tab compact and acknowledge a complete
-- snapshot only after every row has been written successfully.
begin;

-- Repacking needs to update existing physical row numbers. BY DEFAULT keeps
-- automatic numbering for new records while allowing the sync worker to move
-- rows during compaction.
alter table public.appointment_sheet_sync
  alter column sheet_row set generated by default;

create or replace function public.claim_appointment_sheet_sync()
returns table(appointment_id uuid, sheet_row bigint, version bigint, lease_token uuid, payload jsonb)
language sql security definer set search_path = '' as $$
  with candidate as (
    select q.appointment_id from public.appointment_sheet_sync q
    where q.version > q.synced_version and q.retry_at <= now()
      and (q.lease_until is null or q.lease_until < now())
    order by q.retry_at, q.sheet_row
    limit 1 for update skip locked
  ), claimed as (
    update public.appointment_sheet_sync q
    set lease_token = gen_random_uuid(), lease_until = now() + interval '5 minutes'
    from candidate c where q.appointment_id = c.appointment_id returning q.*
  )
  select q.appointment_id, q.sheet_row, q.version, q.lease_token,
    jsonb_build_object(
      'id', a.id, 'reference', a.reference,
      'name', coalesce(a.guest_name, p.full_name, ''),
      'email', coalesce(a.guest_email, p.email, ''),
      'phone', coalesce(a.guest_phone, p.phone, ''),
      'therapist', t.display_name, 'service', s.name,
      'starts_at', a.starts_at, 'ends_at', a.ends_at,
      'modality', a.modality, 'status', a.status,
      'price_cents', a.price_cents, 'currency', a.currency,
      'updated_at', a.updated_at,
      'therapist_id', t.id, 'service_id', s.id
    )
  from claimed q join public.appointments a on a.id = q.appointment_id
  join public.therapists t on t.id = a.therapist_id
  join public.services s on s.id = a.service_id
  left join public.profiles p on p.id = a.client_id;
$$;

-- Reassign rows in their existing order. Negative temporary values avoid the
-- unique constraint while two rows exchange positions.
create or replace function public.compact_appointment_sheet_rows()
returns table(appointment_id uuid, sheet_row bigint, version bigint, synced_version bigint, payload jsonb)
language plpgsql security definer set search_path = '' as $$
begin
  with ranked as (
    select q.appointment_id,
      row_number() over (order by q.sheet_row, q.appointment_id) as position
    from public.appointment_sheet_sync q
  )
  update public.appointment_sheet_sync q
  set sheet_row = -ranked.position
  from ranked
  where q.appointment_id = ranked.appointment_id;

  with ranked as (
    select q.appointment_id,
      row_number() over (order by q.sheet_row desc) as position
    from public.appointment_sheet_sync q
    where q.sheet_row < 0
  )
  update public.appointment_sheet_sync q
  set sheet_row = ranked.position + 1
  from ranked
  where q.appointment_id = ranked.appointment_id;

  return query
  select q.appointment_id, q.sheet_row, q.version, q.synced_version,
    jsonb_build_object(
      'id', a.id, 'reference', a.reference,
      'name', coalesce(a.guest_name, p.full_name, ''),
      'email', coalesce(a.guest_email, p.email, ''),
      'phone', coalesce(a.guest_phone, p.phone, ''),
      'therapist', t.display_name, 'service', s.name,
      'starts_at', a.starts_at, 'ends_at', a.ends_at,
      'modality', a.modality, 'status', a.status,
      'price_cents', a.price_cents, 'currency', a.currency,
      'updated_at', a.updated_at,
      'therapist_id', t.id, 'service_id', s.id
    )
  from public.appointment_sheet_sync q
  join public.appointments a on a.id = q.appointment_id
  join public.therapists t on t.id = a.therapist_id
  join public.services s on s.id = a.service_id
  left join public.profiles p on p.id = a.client_id
  order by q.sheet_row;
end;
$$;

-- A booking can be inserted while Google is being written. Only acknowledge
-- the versions included in the snapshot; newer versions remain queued.
create or replace function public.finish_appointment_sheet_compaction(p_rows jsonb)
returns void language sql security definer set search_path = '' as $$
  with incoming as (
    select appointment_id, version
    from jsonb_to_recordset(coalesce(p_rows, '[]'::jsonb))
      as rows(appointment_id uuid, version bigint)
  )
  update public.appointment_sheet_sync q
  set synced_version = q.version,
      synced_at = now(),
      attempts = 0,
      retry_at = now(),
      last_error = null,
      lease_token = null,
      lease_until = null
  from incoming
  where q.appointment_id = incoming.appointment_id
    and q.version = incoming.version;
$$;

revoke all on function public.compact_appointment_sheet_rows() from public, anon, authenticated;
revoke all on function public.finish_appointment_sheet_compaction(jsonb) from public, anon, authenticated;
grant execute on function public.compact_appointment_sheet_rows() to service_role;
grant execute on function public.finish_appointment_sheet_compaction(jsonb) to service_role;

commit;
